Added endpoints for Survey Module
digital-boss/n8n-nodes-humhub pull request #2
Opened 2023-01-14 10:52 UTC by funkycram

2023-01-16 23:06 UTC, valentina98 requested changes
Please fix and test all of the added endpoints

2023-01-16 23:06 UTC, valentina98 commented on package.json
> +    "version": "0.1.8",
Would you change the number back to version 0.1.7. We use the `npm version 0.1.8` command which runs the versioning scripts and adds an automatic commit.

2023-01-16 23:06 UTC, valentina98 commented on nodes/version.ts
> +export const version = '0.1.8';
Would you change the number back to version 0.1.7. We use the `npm version 0.1.8` command which runs the version script and adds an automatic commit.

2023-01-16 23:06 UTC, valentina98 commented on nodes/HumHub/HumHub.node.ts
> +                        }
There is a build error:

![image](https://user-images.githubusercontent.com/16666577/212776777-9365297e-2560-4cba-95b0-2c556f6384e2.png)

2023-01-16 23:06 UTC, valentina98 commented on nodes/HumHub/descriptions/SurveyDescription.ts
> +        },
Please format the file

2023-01-16 23:06 UTC, valentina98 commented on nodes/HumHub/descriptions/SurveyAnswerDescription.ts
> +        typeOptions: {
Please format the file

2023-01-18 14:14 UTC, funkycram commented
Thanks @valentina98 for your review. It should be correct now. Sorry, but I have no knowledge with npm, so I don't know how to build to test the endpoints...

2023-01-20 12:39 UTC, samuk approved these changes
@valentina98 would it be possible to review this please?

2023-01-26 14:14 UTC, merged

2023-01-26 15:31 UTC, funkycram commented
Thanks @valentina98 for merging this PR!
Could you create the new version with `npm version 0.1.8`?
Thanks